import{d as M,j as r,a as l}from"./assets/client-CYlhr6lt.js";const L={"paypal.com":{name:"PayPal",selectors:['[data-testid="submit-button"]','[data-testid="send-money-submit"]','button[name="payment-submit-btn"]',"#payment-submit-btn","button.send-money-submit","#sendMoneyButton",".paypal-button"]},"venmo.com":{name:"Venmo",selectors:['button[data-testid="pay-button"]','button[aria-label="Pay"]']},"zellepay.com":{name:"Zelle",selectors:["#send-money-zelle-button","#sendmoney-button",'button[type="submit"]']}},N={"venmo.com":/^(Pay|Pay Now|Send|Send Money)$/i,"zellepay.com":/^Send Money$/i};let u=null;const w=()=>{const o=window.location.hostname;for(const e in L)if(o.includes(e))return{config:L[e],domain:e};return null},P=o=>{const e=document.createElement("style");e.textContent=`
    :host {
      --background: 222 47% 7%;
      --foreground: 210 40% 96%;
      --card: 222 40% 10%;
      --card-foreground: 210 40% 96%;
      --primary: 187 92% 69%;
      --secondary: 222 30% 16%;
      --destructive: 0 86% 71%;
      --destructive-foreground: 222 47% 7%;
      --border: 217 30% 15%;
    }
    .fixed { position: fixed; inset: 0; z-index: 2147483647; display: flex; align-items: center; justify-content: center; background-color: rgba(0, 0, 0, 0.7); backdrop-filter: blur(8px); }
    .bg-card { background-color: hsl(var(--card)); border: 1px solid hsl(var(--border)); border-radius: 1.5rem; padding: 2rem; width: 90%; max-width: 400px; box-shadow: 0 0 40px rgba(187, 92, 69, 0.2); }
    .text-center { text-align: center; }
    .font-bold { font-weight: 800; color: #F1F5F9; }
    .text-sm { font-size: 0.875rem; line-height: 1.6; color: #94A3B8; margin: 1.5rem 0; }
    .flex { display: flex; gap: 1rem; }
    .btn { flex: 1; padding: 0.75rem; border-radius: 1rem; font-weight: 700; cursor: pointer; border: none; transition: 0.2s; }
    .btn-secondary { background: #1E293B; color: #94A3B8; }
    .btn-destructive { background: #F87171; color: #0B1120; }
    .btn:hover { opacity: 0.9; transform: scale(1.02); }
  `,o.appendChild(e)},B=()=>{var b;const[o,e]=l.useState(!1),[c,A]=l.useState(null),f=l.useRef(w()),d=l.useRef(!1);if(l.useEffect(()=>{const p=f.current;if(!p)return;const{config:h,domain:R}=p,y=n=>{if(h.selectors.some(t=>n.matches(t)||n.closest(t)))return!0;const s=N[R];if(s){const t=n.tagName==="BUTTON"?n:n.closest("button");if(t){const i=(t.textContent??"").trim().replace(/\s+/g," ");if(s.test(i))return!0}}return!1},g=n=>{var T;const s=n.target;if(!y(s)||(n.preventDefault(),n.stopImmediatePropagation(),d.current))return;d.current=!0;const t=document.querySelector('textarea, [contenteditable="true"], input[name*="note"], input[name*="memo"]');let i="";t instanceof HTMLTextAreaElement||t instanceof HTMLInputElement?i=t.value??"":t instanceof HTMLElement&&(i=t.textContent??"");const v=document.querySelector('input[type="number"], .amount-input, input[name*="amount"]'),C=v instanceof HTMLInputElement?v.value:"",E=parseFloat(C),j=isFinite(E)?E:0;if(!((T=chrome.runtime)!=null&&T.id)){d.current=!1;return}chrome.runtime.sendMessage({type:"ANALYZE_RISK",data:{message:i.substring(0,1e3),amount:j,platform:h.name}},a=>{d.current=!1,a&&typeof a=="object"&&typeof a.riskLevel=="string"&&typeof a.score=="number"&&(a.riskLevel==="high"||a.riskLevel==="critical")&&(A(a),e(!0))})};document.addEventListener("click",g,{capture:!0});const S=()=>{const n=document.querySelectorAll('button, [role="button"]');let s=!1;n.forEach(t=>{!s&&y(t)&&(s=!0)})},x=new MutationObserver(n=>{u!==null&&clearTimeout(u),u=setTimeout(()=>{u=null,S()},200)});return x.observe(document.body,{childList:!0,subtree:!0}),()=>{document.removeEventListener("click",g,!0),x.disconnect()}},[]),!o||!c)return null;const m=(b=f.current)==null?void 0:b.config;return r.jsx("div",{className:"fixed",children:r.jsxs("div",{className:"bg-card text-center",children:[r.jsx("h2",{className:"font-bold",children:c.riskLevel==="critical"?"CRITICAL THREAT DETECTED":`Security Alert: ${(m==null?void 0:m.name)??"Payment"}`}),r.jsx("p",{className:"text-sm",children:c.recommendation||"We've detected potential fraud patterns in this transaction."}),r.jsxs("div",{className:"flex",children:[r.jsx("button",{className:"btn btn-secondary",onClick:()=>e(!1),children:"Cancel Payment"}),r.jsx("button",{className:"btn btn-destructive",onClick:()=>{e(!1),console.warn("[Shield] User ignored high-risk warning.")},children:"Proceed Anyway"})]})]})})},k=()=>{if(!w()||document.getElementById("shield-host"))return;const o=document.createElement("div");o.id="shield-host",document.body.appendChild(o);const e=o.attachShadow({mode:"closed"});P(e);const c=document.createElement("div");e.appendChild(c),M(c).render(r.jsx(B,{}))};document.readyState==="loading"?document.addEventListener("DOMContentLoaded",k,{once:!0}):k();
